SBTM to PCTM to BSM2 reductions and compilers cleanups
uds-psl/coq-library-undecidability pull request #144
Opened 2022-02-20 21:33 UTC by DmxLarchey

This PR is draft intended to be merged after #143. It contains several things:
- a `PCTM` seed close to `SBTM` but fitting the framework of PC-based machines like `BSM` and `MM`. This allows to use the generic compiler to reduce from `PCTM`;
- `PCTM` manipulate the same tape as `SBTM` but their transitions are decomposed (or micro-programmed) into:
  - `WR b`, write Boolean `b` under the head;
  - `MV d`, move the head in direction `d`;
  - `JZ i`, conditional jump after reading the head, to `i` if `false`, and to `1+PC` if `true`;
  - `JMP i`, unconditional jump to `i`.
- provided is a compiler from `SBTM` to `PCTM` and hence a reduction between the halting problems;
- provided is a compiler from `PCTM` to `BSM(2)` (with two stacks only);
- I have reworked the `compiler_correctness.v` framework with a better abstraction: a `compiler_t` record type and several consequence that derive from the `compiler_t` object;
- I have cleaned up and shortened the `BSM(n)` to `MM(n+2)` compiler using that new framework;
- I have cleaned up and shortness the `MMA(n)` to `MMA(n)` re-linker that redirects every terminating jump to the end of the code to get a simple reduction `MMA_HALT` to `MMA_HALT_ZERO`.

2022-02-21 08:17 UTC, mrhaandi commented
Is there a benefit to have two jump instructions
`pctm_sss_jz i j t :   JZ j // (i,t) -1> (if rd t then 1+i else j,t)`, `pctm_sss_jmp i j t : JMP j // (i,t) -1> (j,t)`
Instead of a combined conditional jump, e.g.
`pctm_sss_jc i j1 j2 t :   JC j1 j2 // (i,t) -1> (if rd t then j1 else j2, t)`?
An unconditional jump is then setting `j1=j2=j`?

2022-02-21 08:34 UTC, DmxLarchey commented
> Is there a benefit to have two jump instructions ...

May be I am still influenced by the days (long time ago) where I did actually program x86 in MASM ;-) No I do not think there is a major reason for having `JZ`/`JMP` and I will replace them with `BR i j` (for say _branch_) but I am taking any suggestion for a better acronym: `ITE` (for _if then else_)...?

2022-04-12 13:46 UTC, mrhaandi commented
With the cleaned up framework, is it easy to get `MMA_HALTING (3+n) <= MMA_HALTING (2+n)`?

2022-04-12 14:21 UTC, DmxLarchey commented on theories/Shared/Libs/DLW/Code/compiler_correction.v
> -  (* ** A Syntactically Correct Compiler *)
Here is the definition for the abstract compiler.

2022-04-12 14:59 UTC, mrhaandi commented
> For the moment the reduction is `MMA_HALTING (n) <= MMA_HALTING (2)` but via `FRACTRAN` which may be the step you would like to avoid?

Is it? I could not find any lemma that starts from `MMA_HALTING (n)` (only `MM`, but not `MMA`).
Correct me if I am wrong, but the `MM` is the discouraged one, and `MMA` is preferred.
I also did not find `MMA_HALTING (n)` to any `FRACTRAN` problem.

2022-04-12 15:23 UTC, DmxLarchey commented
> Is it? I could not find any lemma that starts from `MMA_HALTING (n)` (only `MM`, but not `MMA`). Correct me if I am wrong, but the `MM` is the discouraged one, and `MMA` is preferred. I also did not find `MMA_HALTING (n)` to any `FRACTRAN` problem.

Sure, sorry for my imprecision. Indeed, the reduction which exists right now is `MM(n) <= MM_noloop(1+n) <= FRACTRAN <= MMA(2)` (FSCD 2019 & 2021). What I meant is probably you do not want the below chain

`MMA(3+n) <= MM(4+n) <= MM_noloop(5+n) <= FRACTRAN <= MMA(2) <= MMA(2+n)`

which potentially exists up to the easy/trivial:
+ `MMA(n) <= MM(1+n)`, using a zero valued extra counter for univ. jump;
+ `MMA(2) <= MMA(2+n)`, by mapping `pos 2` to `pos 2+n`) reductions.

2022-06-09 14:50 UTC, mrhaandi commented
@DmxLarchey After the `Proof Using "Type"` PR you do not need to write `Proof using .` anymore (as I noticed you started doing) as both the ide and batch compiler assumes `Proof using Type.` automatically. You only need to add annotation where you use more hypotheses than occur in the goal type.

2022-06-11 12:15 UTC, DmxLarchey commented
Added `MMA_HALT(3+n)` to `MMA_HALT(2+n)` reduction based on a certified compiler. It was not so long (one day of work) after all. @mrhaandi sorry for the delay. I will complete the presentation of this PR for a better description.

2022-06-11 12:21 UTC, DmxLarchey commented
The proof of soundness of the compiler is still a bit redondant though.

2022-06-12 06:14 UTC, DmxLarchey commented
@mrhaandi Iterating `MMA_HALTING (3+n) ⪯ MMA_HALTING (2+n)` would give a `MMA_HALTING (2+n) ⪯ MMA_HALTING 2` reduction but one could also possibly write a direct compiler from `mma_sss (k+2)` to `mma_sss 2` using the same technique. Would this be of interest to you?

2022-06-12 06:36 UTC, mrhaandi commented
> direct compiler from `mma_sss (k+2)` to `mma_sss 2` using the same technique. Would this be of interest to you?

The actual underlying technique is `3+n` to `2+n`. Unless time/space complexity is of concern, (here it is not) compressing the iteration into one step (basically inlining the induction) is not too interesting.

2022-06-13 14:08 UTC, DmxLarchey commented
@yforster and @mrhaandi
This PR is not intrusive, meaning there are only minor changes to my own code and extensions that are orthogonal to existing results. For instance, the legacy compiler framework still works but the newer one is cleaner IMHO.

I propose to merge in`coq-8.15` soon if no one objects.

2022-06-13 14:10 UTC, yforster approved these changes

2022-06-13 14:52 UTC, mrhaandi commented
> I propose to merge in`coq-8.15` soon if no one objects.

There are still several pending review comments from my initial review, and I recently added more (review see above).

2022-06-13 20:13 UTC, DmxLarchey commented
> ... An unconditional jump is then setting `j1=j2=j`?

Done as `BR` (for branch), see below.

2022-06-13 20:21 UTC, DmxLarchey commented
> @DmxLarchey After the `Proof Using "Type"` PR you do not need to write `Proof using .` anymore (as I noticed you started doing) as both the ide and batch compiler assumes `Proof using Type.` automatically. You only need to add annotation where you use more hypotheses than occur in the goal type.

@mrhaandi I did clean the code up regarding the `Proof using` issues.

2022-06-13 20:28 UTC, DmxLarchey commented
@mrhaandi I fixed two issues

- clean `Proof using.` and related issues;
- replace `JZ`/`JMP` with a singe branch instruction `BR`.

Are there any other pending issues from your point of view ?

2022-06-14 08:36 UTC, DmxLarchey commented
> I'm not sure whether you can see my review comments. 

Ok this is why I do not get what you ask me to do. No I *do not see* those comments:

- neither in the GH interface `Conversation` item;
- nor in the `Files changed` item of the GH interface.
- and your review status is marked `awaiting ...` 

@yforster Can you see these comments that I do not see ?

2022-06-14 08:43 UTC, mrhaandi requested changes

2022-06-14 08:44 UTC, mrhaandi commented
> No I _do not see_ those comments

Hopefully now. I marked those as blocking.

2022-06-14 08:46 UTC, DmxLarchey commented
> > No I _do not see_ those comments
> 
> Hopefully now. I marked those as blocking.

Ok thx I will look at those issues.

2022-06-14 08:47 UTC, DmxLarchey commented on theories/TM/PCTM/pctm_sbtm.v
> +Set Default Proof Using "Type".
Done yesterday.

2022-06-14 13:12 UTC, DmxLarchey commented on theories/Shared/Libs/DLW/Code/compiler_correction.v
> +    Let complete : forall P i, compiled_complete (link P i) P (i,code P i).
Fixed the issue in commit 38d220b9fb7042daa85147c03072cb7ec6c32d81

2022-06-14 13:17 UTC, DmxLarchey commented
In commit 0afe51a5b2b2fc50d988cf6fee3cdccfbc9e2cdb, I did abstract away `godel_coding` through a `Record` type and then factored the `MMA(3+n)` to `MMA(2+n)` compiler into a `MMA(k+n)` to `MMA (2+n)` compiler, requiring a `godel_coding : vec nat k -> nat`.

Generated:
  - `godel_coding : vec 3 nat -> nat` based on `2^a.3^b.5^c`;
  - `godel_coding : vec 4 nat -> nat` based on `2^a.3^b.5^c.7^d`.

Then I straightforwardly derive compilers and reductions:
  - `MMA(3+n)` to `MMA(2+n)`
  - `MMA(4)` to `MMA(2)`
  
  as direct instances.

2022-06-14 13:29 UTC, DmxLarchey commented on theories/StackMachines/BSM/bsm_defs.v
>      simpl; lia.
Thx for the  suggestion `Set Default Goal Selector "!"`. I will try to use it more systematically to check for the fine structure of proofs.

2022-06-14 13:31 UTC, DmxLarchey commented on theories/StackMachines/BSM/bsm_defs.v
>      simpl; lia.
Fixed but maybe not quite systematically over all my old code. I will have to parse it but maybe this is for a separate PR.

2022-06-14 13:38 UTC, mrhaandi approved these changes

2022-06-14 13:42 UTC, DmxLarchey commented
> Adding hints to `core` can become a bothersome (reliability/performance) transitively included side effect. It is recommended to use specialized hint databases instead.

I usually do not use this globally (outside sections) but I possibly could have made such an unrecommended global hint.

2022-06-14 13:46 UTC, mrhaandi commented
> Because I intend to complete `... ⪯ SBTM ⪯ PCTM ⪯ BSM(2) ⪯ MMA(4) ⪯ MMA(2)` hence getting a path to `MMA(2)` avoiding
> `FRACTRAN`.

This is a good idea. However, why not then show the use of `MMA(3+n) ⪯ MMA(2+n)` by `MMA(3+1) ⪯ MMA(2+1=3+0) ⪯ MMA(2+0)`? Adding quadruple Gödel coding for this.

2022-06-14 13:50 UTC, mrhaandi commented
By the way, I will at some later point look whether I can use your Gödel record for my ad-hoc
https://github.com/uds-psl/coq-library-undecidability/blob/574817d704d6b583379ae8071be30f1788fb6b94/theories/CounterMachines/Reductions/CM2_HALT_to_CM1_HALT.v#L75

2022-06-15 16:02 UTC, DmxLarchey commented
> By the way, I will at some later point look whether I can use your Gödel record for my ad-hoc

- The `godel_coding.v` file now belongs to the same dir. as `gcd.v` and `prime.v`. 
- Please let me know if the abstraction suits your needs, eg `a,c,b => 13.6^a.7^b.55^c` would also satisfy the `godel_coding` axioms. May be you need more properties for what you do with `2^a.3^b.5^c`.

2022-06-15 16:12 UTC, DmxLarchey commented
> ... by `MMA(3+1) ⪯ MMA(2+1=3+0) ⪯ MMA(2+0)`? Adding quadruple Gödel coding for this.

Because the proof of `MMA(k+n) ⪯ MMA(2+n)` is only a very light (and straightforward) generalization of  `MMA(3+n) ⪯ MMA(2+n)` once you abstracted away the `godel_coding`, then the two paths:

- `MMA(3+1) ⪯ MMA(2+1=3+0) ⪯ MMA(2+0)` (with two `godel_coding 3` combined) 
- `MMA(4+0) ⪯ MMA(2+0)` (with one `godel_coding 4`)

have roughly the same code size, very small. Of course, one needs `godel_coding 4` which duplicates some trivial code from `godel_coding 3`. I guess one could also prove ` a <= b -> godel_coding b -> godel_coding a` quite easily and then just derive `godel_coding 3` from `godel_coding 4`. In the `FRACTRAN` code of course, there is a hidden proof of `godel_coding  n`.

2022-06-15 20:03 UTC, mrhaandi commented
@DmxLarchey feel free to merge anytime.

2022-06-17 09:19 UTC, merged